@import exercise.dto.articles.BuildArticlePage
@param BuildArticlePage page

<html>
<head>
    <meta charset="UTF-8">
</head>
<body>
@if(page.getErrors() != null)
    <ul>
        @for(var validator : page.getErrors().values())
            @for(var error : validator)
                <li>${error.getMessage()}</li>
            @endfor
        @endfor
    </ul>
@endif

<form action="/articles" method="post">
    <div>
        <label>
            Название статьи
            <input type="text" name="title" value="${page.getTitle()}"/>
        </label>
    </div>
    <div>
        <label>
            Содержимое статьи
            <input type="text" name="content" value="${page.getContent()}"/>
        </label>
    </div>
    <input type="submit" value="Отправить"/>
</form>
</body>
</html>
